[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"
watchPatterns = []

[deploy]
startCommand = "node kaya_server.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3



